server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://banco:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
