version: '3.8'
services:
  banco:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  microservico-alunos:
    build:
      context: ./microservico-alunos
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      banco:
        condition: service_healthy
    ports:
      - "8081:8081"
  microservico-disciplinas:
    build:
      context: ./microservico-disciplinas
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      banco:
        condition: service_healthy
    ports:
      - "8082:8082"

volumes:
  pgdata:
